### ISSUE TITLE
Allow playbook version to be any term, no need for x.x.x constraint

### ISSUE THREAD

**Issue by miopa** [FarmRadioHangar/boxter#2] opened 2017-04-09 23:55 UTC

**Comment by miopa** [comment] 2017-04-10 00:57
```
No Major.Minor.Patch elements found
```
This is the error I got, I tried using miopa-dev as version.

But then, i reverted to x.x.x version, and I still get this error, so something else is going on.

**Comment by gernest** [comment] 2017-04-10 07:18
@miopa  im sorry but I can't make this change. We are using semantic versioning. Which strictly states how to version your software.

It makes it easy to compare and find how latest a version is. `0.1.2` is less than `0.1.4`. I can make the change for the sake of making you happy, but trust me when I say It is not worthy it.

You can instead change the directories where the playbooks are  like have a playbook dir point ot `/mlopa-de/` then drop the version there. Probalby you will have the same effect you desired.

**Comment by miopa** [comment] 2017-04-10 10:06
I can't change the playbook dir, it's one per server.

The change is not to make me happy, but to make this more usable. There is not a need anywhere in the system to know how 'latest' is a version, just that it's different.

**Comment by miopa** [comment] 2017-04-10 10:29
I figured out the issue, it's failing if there is a folder not named x.x.x in the playbook dir. The problem with changing the playbook dir is that I don't call boxter manually, it's called by shell-script when any box connects.

I guess I can make some hack to make boxes with -dev in the hostname to load different config, but in essence, the versioning of the playbooks is not 'semantic', you can have playbooks with different versions of roles that are not newer or older in any meaningful way

**Comment by gernest** [comment] 2017-04-28 17:29
@miopa I'm closing this, feel free to reopen if the problem is still there

**Closed as completed by gernest** 2017-04-28 17:29 UTC
